### ISSUE TITLE
Collision Detection Bug(The Sad Tragedy of Micro-Optimization Theater II:Coding Horror Boogaloo)

### ISSUE THREAD

**Issue by virtuoushub** [Hornswaggler/fuzzy-octo-shame#61]
If you hit a tile's corner at just the right point, issues like the image below where the player is not falling down but actually standing on the wall's tile will occur.

![collisionfail](https://cloud.githubusercontent.com/assets/4303638/5695790/b377f0fc-9980-11e4-9cc0-63594b55440b.png)

I have also noticed when jumping up to a tile that you can make it into, but because of a mistimed jump you should not be able to get to, this bug allows you to "pop" to the top on ledge thereby lowering the skills needed for precision timing of jumps.

Somewhere along the misguided path of my micro-optimization, I suspect I introduced this bug. I modified the original code to do some cheeky floating point ~~arithmetic~~ comparisons which most likely caused the observed problem.

**Comment by virtuoushub** [comment]
Fixed with [0.1.11 release](https://github.com/Hornswaggler/fuzzy-octo-shame/tree/0.1.11)

**Comment by Hornswaggler** [comment]
This used to happen, there was probably a band aid somewhere in there that
prevented it
On Jan 11, 2015 11:10 AM, "Peter Colapietro" <notifications@github.com>
wrote:
>
> If you hit a tile's corner at just the right point, issues like the image
below where the player is not falling down but actually standing on the
wall's tile will occur.
>
> I have also noticed when jumping up to a tile that you can make it into,
but because of a mistimed jump you should not be able to get to, this bug
allows you to "pop" to the top on ledge thereby lowering the skills needed
for precision timing of jumps.
>
> Somewhere along the misguided path of my micro-optimization, I suspect I
introduced this bug. I modified the original code to do some cheeky
floating point arithmetic which most likely caused the observed problem.
